services:
  jansen-bot:
    build: .
    image: jansen-bot:latest
    ports:
      - "8080:8080"
    environment:

      BOT_DB_URL: ${BOT_DB_URL}
      BOT_DB_USER: ${BOT_DB_USER}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}

    depends_on:
        postgres-bot:
            condition: service_healthy

  postgres-bot:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${BOT_DB_USER}
      POSTGRES_PASSWORD: ${BOT_DB_PASSWORD}
      POSTGRES_DB: ${BOT_DB_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${BOT_DB_USER}", "-d", "${BOT_DB_DB}"]
      interval: 10s # de em quanto em quanto tempo o teste roda
      timeout: 5s # quanto tempo espera
      retries: 5 #quantas tentativas

    volumes:
      - postgres-bot-data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass redispassword

  evolution-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${EVOLUTION_DB_USER}
      POSTGRES_PASSWORD: ${EVOLUTION_DB_PASSWORD}
      POSTGRES_DB: ${EVOLUTION_DB_DB}

volumes:
    postgres-bot-data: