services:
  jansen-bot:
    build: .
    image: jansen-bot:latest
    ports:
      - "8080:8080"
    environment:
      BOT_DB_URL: ${BOT_DB_URL}
      BOT_DB_USER: ${BOT_DB_USER}
      BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
      EVOLUTION_API_KEY: ${EVOLUTION_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GOOGLE_SHEETS_ID: ${GOOGLE_SHEETS_ID}
      BANDA_ADMIN_PHONES: ${BANDA_ADMIN_PHONES}
      BANDA_NOME: ${BANDA_NOME}

    depends_on:
        postgres-bot:
            condition: service_healthy

  postgres-bot:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${BOT_DB_USER}
      POSTGRES_PASSWORD: ${BOT_DB_PASSWORD}
      POSTGRES_DB: ${BOT_DB_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${BOT_DB_USER}", "-d", "${BOT_DB_DB}"]
      interval: 10s # de em quanto em quanto tempo o teste roda
      timeout: 5s # quanto tempo espera
      retries: 5 #quantas tentativas

    volumes:
      - postgres-bot-data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass redispassword
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redispassword", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  evolution-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${EVOLUTION_DB_USER}
      POSTGRES_PASSWORD: ${EVOLUTION_DB_PASSWORD}
      POSTGRES_DB: ${EVOLUTION_DB_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${EVOLUTION_DB_USER}", "-d", "${EVOLUTION_DB_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - evolution-postgres-data:/var/lib/postgresql/data

  evolution-api:
    image: evoapicloud/evolution-api:v2.3.7
    ports:
      - "8081:8080"
    environment:
        SERVER_URL: ${EVOLUTION_SERVER_URL}
        AUTHENTICATION_API_KEY: ${EVOLUTION_API_KEY}
        DATABASE_ENABLED: "true"
        DATABASE_PROVIDER: postgresql
        DATABASE_CONNECTION_URI: postgresql://${EVOLUTION_DB_USER}:${EVOLUTION_DB_PASSWORD}@evolution-postgres:5432/${EVOLUTION_DB_DB}
        DATABASE_SAVE_DATA_INSTANCE: "true"
        DATABASE_SAVE_DATA_NEW_MESSAGE: "true"
        CACHE_REDIS_ENABLED: "true"
        CACHE_REDIS_URI: redis://:redispassword@redis:6379/0
        WEBHOOK_GLOBAL_ENABLED: "false"
    volumes:
      - evolution-instances:/evolution/instances
    depends_on:
        evolution-postgres:
            condition: service_healthy
        redis:
          condition: service_healthy
volumes:
    postgres-bot-data:
    evolution-postgres-data:
    evolution-instances: